#!/usr/bin/env python3
"""Inject Mainsail/Fluidd gcode thumbnails (from PNG files) into a gcode.

OrcaSlicer's headless CLI does NOT render thumbnails (no GL context over SSH),
so Mainsail/Fluidd show no preview next to our uploaded files. This embeds the
standard `; thumbnail begin WxH <b64len>` PNG blocks that Moonraker extracts
into its `.thumbs` cache and the web UI displays.

Pass PNGs already sized to the WxH you want (render them with OpenSCAD, e.g.
`openscad -o p.png --imgsize=300,300 --viewall --autocenter -D 'part="funnel"' m.scad`).
Give both a small (e.g. 48x48, list icon) and a large (e.g. 300x300, detail).

Usage (runs wherever the gcode is):
    python3 pf_thumb.py <gcode> <png> [<png2> ...]
"""
import sys, base64, struct

def png_wh(data):
    # PNG = 8-byte sig + IHDR chunk (len, 'IHDR', width u32, height u32)
    return struct.unpack(">II", data[16:24])

def make_block(data):
    w, h = png_wh(data)
    b64 = base64.b64encode(data).decode()
    rows = [b64[i:i+78] for i in range(0, len(b64), 78)]
    return "\n".join(["; thumbnail begin %dx%d %d" % (w, h, len(b64))]
                     + ["; " + r for r in rows] + ["; thumbnail end"])

def main():
    if len(sys.argv) < 3:
        sys.exit("usage: pf_thumb.py <gcode> <png> [<png2> ...]")
    gcode, pngs = sys.argv[1], sys.argv[2:]
    blocks = [make_block(open(p, "rb").read()) for p in pngs]
    thumb = ";\n" + "\n;\n".join(blocks) + "\n;\n"
    src = open(gcode).read()
    nl = src.find("\n") + 1            # keep the "; generated by ..." first line
    open(gcode, "w").write(src[:nl] + thumb + src[nl:])
    print("injected %d thumbnail(s) into %s" % (len(pngs), gcode))

if __name__ == "__main__":
    main()
